name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]   # En PR: construye pero NO publica
  push:
    branches: [ "main" ]   # En main: construye y publica
  workflow_dispatch:       # Permite lanzarlo manualmente desde la UI

env:
  IMAGE_BACKEND: magalisar123/delilunch-backend-sarmiento
  IMAGE_FRONTEND: magalisar123/delilunch-frontend-sarmiento

jobs:
  build_pr:
    if: github.event_name == 'pull_request'
    name: Build images (no push)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image (no push)
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false

      - name: Build frontend image (no push)
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false

  publish_main:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Build & Push images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # üîê Login a Docker Hub con tus secrets personales
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # üß± Construir y subir backend
      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_BACKEND }}:latest
            ${{ env.IMAGE_BACKEND }}:${{ github.sha }}

      # üß± Construir y subir frontend
      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_FRONTEND }}:latest
            ${{ env.IMAGE_FRONTEND }}:${{ github.sha }}

      # üöÄ Desplegar autom√°ticamente en Render
      - name: Enviar a Render
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_BACKEND}}&imageUrl=${{secrets.DOCKERHUB_USERNAME}}/delilunch-backend-sarmiento:latest"
        # curl viene con ubuntu es para abrir http osea links
        # -X es para que sea una peticion
        # POST es de http que es para eviar datos (chekear)


